version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - app.env
    environment:
      - GO_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=mydatabase
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
