version: "3"

tasks:
  dev:
    cmds:
      - air

  build:
    cmds:
      - go build -o http-server cmd/http/main.go

  start:
    cmds:
      - ./http-server

  install:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/go-task/task/v3/cmd/task@latest

  create-migration:
    cmds:
      - go run cmd/migration/migrate.go --action=create-migration --table={{.CLI_ARGS}}

  migrate:
    cmds:
      - go run cmd/migration/migrate.go --action={{.CLI_ARGS}}
